name: "@joaomarcuslf.com - Full-stack Software engineer"
description: I'm Software Engineer since 2015 with great expertise in Front-end development. I like to teach a lot, and write some posts, you can check more here.
author: João Marcus de Lemos Fernandes
canonical: http://joaomarcuslf.com/
keywords: Developer, Software engineer, Front-end, Full-stack, React, Javascript, Flask, Python, Joaomarcuslf, Tech Mentor, Mentorship, Mentoria, Senior Developer, Web development
abstract: My presentation website as Software developer
avatar: https://avatars0.githubusercontent.com/u/53450523?s=400&u=ba2eb6e6c63bc38c54e7db04e5132c833a83169c&v=4
email: jmarcusfernandes@gmail.com
linktr: https://linktr.ee/joaomarcuslf
github: https://github.com/joaomarcuslf
linkedin: https://www.linkedin.com/in/jo%C3%A3o-marcus-fernandes-4b8814ba
medium: https://joaomarcuslf.medium.com
codewars: https://www.codewars.com/users/joaomarcuslf/following
sourcerer: https://sourcerer.io/joaomarcuslf
twitter: https://twitter.com/joaomarcuslf

collections:
  posts:
    output: true
    permalink: /:collection/:name
  skills:
    output: false
    permalink: /:collection/:name
  projects:
    output: false
    permalink: /:collection/:name
  jobs:
    output: false
    permalink: /:collection/:name
  graduations:
    output: false
    permalink: /:collection/:name
  qualifications:
    output: false
    permalink: /:collection/:name

google_analytics:

url: http://joaomarcuslf.com

baseurl: ""

permalink: /:title/

version: v2.5.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

resume:
  name: João Marcus de Lemos Fernandes
  age: 25
  email: jmarcusfernandes@gmail.com
  mobile: (21) 98843-2606
  site: http://joaomarcuslf.com/
  pt:
    from: Rio de Janeiro, Brasil
  en:
    from: Rio de Janeiro, Brazil
  skype: joao_marcus_l
  github: https://github.com/joaomarcuslf
  linkedin: linkedin.com/in/joaomarcuslf
  skills:
    hard:
      pt:
        - Javascript
        - 'React.js'
        - 'Vue.js'
        - 'Node.js'
        - 'ExpressJS'
        - 'Mocha + Chai.js'
        - Jest
        - SCSS
        - SQL
        - PostgreSQL
        - MongoDB
        - Go
        - Python
        - Flask
        - Ruby
        - 'Ruby on Rails'
        - R
        - Git
        - Agile
        - Webpack
        - Docker
        - Linux
        - Rest
        - AWS
        - Clean Code
        - Estatística
        - Matemática Discreta
        - Visualização de dados
        - Desenvolvimento Cloud
      en:
        - Javascript
        - 'React.js'
        - 'Vue.js'
        - 'Node.js'
        - 'ExpressJS'
        - 'Mocha + Chai.js'
        - Jest
        - SCSS
        - SQL
        - PostgreSQL
        - MongoDB
        - Golang
        - Python
        - Flask
        - Ruby
        - 'Ruby on Rails'
        - R
        - Git
        - Agile
        - Webpack
        - Docker
        - Linux
        - Rest
        - AWS
        - Clean Code
        - Statistics
        - Math
        - Data Visualization
        - Cloud Engineering

    soft:
      pt:
        - Resolução de Conflitos
        - Trabalho em Equipe
        - Mentoria
        - Autodidata
        - Troca de Feedback
        - Comunicação não violenta
        - Ownership
        - Proativo
        - Pensamento Crítico
        - Storytelling
        - Detalhista
        - Visão de Negócio
      en:
        - Conflict resolution
        - Team work
        - Mentoring
        - Self-taught
        - Feedback exchange
        - Non-violent communication
        - Ownership
        - Proactive
        - Critical Thinking
        - Storytelling
        - Detail
        - Business Acumen
