name: "@joaomarcuslf.com - Full-stack Web developer"
description: I'm Software developer since 2015 with great expertise in Front-end development. Here you can learn more about my skills and experience.
author: João Marcus de Lemos Fernandes
canonical: http://joaomarcuslf.com/
keywords: Developer, Front-end, Full-stack, React, Javascript, Joaomarcuslf
abstract: My presentation website as SOftware developer
avatar: https://avatars0.githubusercontent.com/u/53450523?s=400&u=ba2eb6e6c63bc38c54e7db04e5132c833a83169c&v=4
email: jmarcusfernandes@gmail.com
linktr: https://linktr.ee/joaomarcuslf
github: https://github.com/joaomarcuslf2
linkedin: https://www.linkedin.com/in/jo%C3%A3o-marcus-fernandes-4b8814ba
medium: https://medium.com/@joaomarcuslf
codewars: https://www.codewars.com/users/joaomarcuslf/following
sourcerer: https://sourcerer.io/joaomarcuslf2
twitter: https://twitter.com/joaomarcuslf

collections:
  posts:
    output: true
    permalink: /:collection/:name
  skills:
    output: false
    permalink: /:collection/:name
  projects:
    output: false
    permalink: /:collection/:name
  jobs:
    output: false
    permalink: /:collection/:name
  graduations:
    output: false
    permalink: /:collection/:name
  qualifications:
    output: false
    permalink: /:collection/:name

google_analytics:

url: http://joaomarcuslf.com

baseurl: ""

permalink: /:title/

version: v2.5.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

resume:
  name: João Marcus de Lemos Fernandes
  age: 24
  email: jmarcusfernandes@gmail.com
  mobile: (21) 98843-2606
  site: http://joaomarcuslf.com/
  pt:
    from: Rio de Janeiro, Brasil
  en:
    from: Rio de Janeiro, Brazil
  skype: joao_marcus_l
  github: https://github.com/joaomarcuslf2
  linkedin: linkedin.com/in/joaomarcuslf
  skills:
    front:
      - Javascript
      - React.js
      - Vue.js
      - SCSS
    back:
      - Node.js
      - Ruby on Rails
      - Django
      - PostgreSQL
    data:
      - Python
      - R
      - Pandas
      - SQL