name: Create Post
on:
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.issue);
            const { author_association, body } = context.payload.comment
  create_file:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.author_association == 'OWNER' }}
    steps:
      - name: Teste
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "_posts/fileName.md"
          FILE_DATA: context.comment.body

