name: Auto feed creator
on:
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: On Issue comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create file from issue payload
        uses: actions/github-script@v4
        with:
          script: |
            let fs = require('fs');

            let { author_association, body, created_at } = context.payload.comment
            let { labels } = context.issue

            if (author_association == 'OWNER') {
              let date = created_at.split("T")[0]

              function getKey(body, key) {
                  return body.split("\r\n").reduce(function (acc, elm) {
                  if (elm.includes(`${key}: `)) {
                    return elm.replace(`${key}: `, '').split('"').join('')
                  }
                  return acc;
                }, "")
              }

              function sanitizeName(name) {
                return name.replace(/[^\w\s]/gi, '').toLowerCase().split(" ").join("-")
              }

              function getFileName(body, layout) {
                switch (layout) {
                  case 'graduation':
                    title = sanitizeName(getKey(body, 'title'))

                    return `${getKey(body, 'end')}-${name}`

                  case 'job':
                    title = sanitizeName(getKey(body, 'company_name'))
                    [month, year] = getKey(body, 'start_date').split('/')

                    return `${year}-${month}-${title}`

                  case 'post':
                    title = sanitizeName(getKey(body, 'title'))

                    return `${date}-${title}`

                  case 'project':
                    title = sanitizeName(getKey(body, 'repo'))

                    return `${date}-${name}`

                  case 'skill':
                    title = sanitizeName(getKey(body, 'name'))

                    return `${name}`

                  default:
                    return ''
                }
              }

              let layout = getKey(body, 'layout')
              fs.writeFileSync( `_${layout}s/${getFileName(body, layout)}.md`, body )
            }

      - name: Commit file
        if: ${{ github.event.comment.author_association == 'OWNER'}}
        uses: EndBug/add-and-commit@v7
        with:
          message: "Auto add file to feed"
