name: Create Post
on:
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');

            const { author_association, body, created_at, title } = context.payload.comment

            if (author_association == 'OWNER') {
              console.log(context.payload.comment)

              const date = created_at.split("T")[0]

              const title = body.split("\r\n").reduce(function (acc, elm) {
                if (elm.includes('title: ')) {
                  return elm.replace('title: ', '').split('"').join('')
                }
                return acc;
              }, "")

              const name = title.replace(/[^\w\s]/gi, '').toLowerCase().split(" ").join("-")

              fs.writeFileSync( `_posts/${date}-${name}`, body )
            }
