name: Create Post
on:
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
          echo "Comment on issue #${{ github.event.issue.body }}"
          echo github.event.issue
