name: Create Post
on:
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.issue);
            console.log(context);
